baseURL = 'https://edgeorge-blog.netlify.app/'
locale = 'en-us'
title = "Ed George's New Reading Marx Blog"
theme = "ananke"
pluralizeListTitles = false
mainSections = ["posts"]
[menu]

  [[menu.main]]
name = "Home"
url = "/"
weight = 1

[[menu.main]]
name = "Reading Marx"
url = "/reading-marx/"
weight = 2

[[menu.main]]
name = "Grundrisse"
parent = "Reading Marx"
url = "/reading-marx/grundrisse/"
weight = 1

[[menu.main]]
name = "Writing"
url = "/writing/"
weight = 3

[[menu.main]]
name = "Texts"
url = "/texts/"
weight = 4

[[menu.main]]
name = "Links"
url = "/links/"
weight = 5

[params]
custom_css = ["css/custom.css"]